@host = http://localhost:8010

### handleRequest
// @no-log
POST {{host}}
Content-Type: application/json

{
  "links": {
    "0": "http://nongnghiep.vn/nongnghiepvn/vi-vn/61/158/1/24/24/58851/default.aspx",
    "1": "https://www.cia.gov/library/publications/the-world-factbook/geos/ch.html",
    "2": "http://iresearch.worldbank.org/PovcalNet/povDuplicateWB.aspx",
    "3": "https://edepot.wur.nl/411162",
    "4": "https://bitnest.netfirms.com/external/JCLIC/2.4.25-28",
    "5": "https://www.mmtimes.com/news/top-ten-kayin-things-experience.html?qt-social_plugin=1",
    "6": "http://www.biopsychiatry.com/lovengf.htm",
    "7": "http://spaceflight.nasa.gov/gallery/audio/shuttle/sts-123/transcript/fd12.txt",
    "8": "http://www.vnnic.vn/",
    "9": "http://www.usa.gov/",
    "10": "http://www.usdebtclock.org/"
  },
  "debug": false
}
